README.md
index.js
test/as-json.js
test/index.js
test/tcurl.js

r @Raynos @kriskowal
Break into two commits per request:
1. tcurl included
2. added a test: as-json.
I will publish the package after merge.

tcurl + as-json test

---

index.js

I needed a raw mode in tcurl to test things. It
defaulted to json >_>...
cc @jcorbin @kriskowal

add a raw mode

---

index.js

r @Raynos @kriskowal 
needs to convert to JSON so that thriftify can take it.

fix a bug in tcurl as thrift

---

index.js
log.js

r: @Raynos @kriskowal 
cc: @anson627 
1. add friendly message for tcurl health ping
2. reduce the size of index.js

add friendly message for tcurl health ping

---

as-http.js
index.js
package.json
test/as-http.js
test/index.js

tcurl as http & test

---

as-http.js
index.js
package.json

fix a bug in as-http

---

index.js
meta-client.js
meta.thrift
test/health.js

For #9
r @Raynos @kriskowal @rf 
cc @xichen2020 @prashantv @jsu1212 @breerly @abhinav @blampe @junchaowu

health check & bug fix

---

meta-client.js
meta.thrift
test/health.js

For #9
Per our discussion.
r @Raynos @kriskowal 
cc @prashantv @breerly @abhinav @blampe @junchaowu

Update the meta IDL

---

index.js
test/as-thrift.js
test/index.js

Fixes #17 
r @Willyham @Raynos @ShanniLi

Fix headers for as-thrift tcurls

---

index.js
test/as-json.js

add a timeout feature

---

index.js

Support thrift header parsing

---

README.md

Add a thrift example

---

meta-client.js

r @jcorbin @kriskowal @shannili

add a proper exit code

---

index.js

As requested by feedback on #26 
r @kriskowal

Use just read + branch on EISDIR

---

as-http.js
index.js
test/as-http.js

pass url in as-http

---

index.js
package.json

r @Raynos @kriskowal 
cc @blampe

better JSON parse error

---

index.js

report message instead of throw an error

---

index.js

remove the listen on ephemeral ports which causes peer leaks in tchannel server

---

as-http.js
package.json
test/as-http.js

fix as-http request

---

index.js
log.js
test/as-http.js

r @Raynos @anson627 @blampe 
node index.js -p 127.0.0.1:21300 hyperbahn Hyperbahn:discover -3 '{"query":"onediretion"}' -j 2>&1 | jq .
{
"message": "Got an error response",
"response": {
"type": "tchannel.bad-request",
"message": "no such endpoint service=\"hyperbahn\" endpoint=\"Hyperbahn:discover\"",
"isErrorFrame": true,
"codeName": "BadRequest",
"errorCode": 6,
"originalId": 2,
"name": "TchannelBadRequestError",
"fullType": "tchannel.bad-request"
}
}

Better json output format

---

index.js

add current version to tcurl cmd line help

---

test/health.js

Validate health output

---

README.md
exit-codes.js
logger.js
test/health.js

Implement meaningful exit codes

---

index.js

Choose a random peer from host list

---

index.js

Allows override for JSON just in case. All other arg schemes are explicit.

Infer as=thrift from endpoint with ::

---

index.js
package.json

This supports a tcurlrc file.
@kriskowal @ShanniLi

Support tcurlrc

---

index.js
man/tcurl.1
package.json
scripts/create-man.sh
usage.md

r @kriskowal @Raynos 
cc @jcorbin

manual for tcurl

---

index.js
man/tcurl.1
usage.md

option to print current version

---

as-http.js
man/tcurl.1
package.json

r @anson627 @ShanniLi @malandrew 
cc @jcorbin

Unlock semver of tchannel and fix back-incompat as-http

---

benchmark-logger.js
benchmark.js
index.js
man/tcurl.1
test/benchmark.js
test/index.js
usage.md

r @Raynos @kriskowal 
cc @breerly 
ref: #68

tcurl benchmark mode: sending a request many times

---

index.js

r @ShanniLi @malandrew @Raynos 
Fixes #84

Display Thrift syntax error metadata

---

logger.js

Provide advice for "no peer available" error

---

.eslintignore
index.js
package.json

Switch to eslint

---

index.js

Provide concise errors for bad or missing configuration

---

index.js

Fixes https://github.com/uber/tcurl/issues/81
@kriskowal @Raynos

Fix logging when unable to read thrift file

---

index.js
test/as-json.js

Fix as=json default body regression

---

test/as-thrift.js

Use new entryPoint for as=thrift

---

index.js
logger.js

Add trace to output

---

.eslintrc
.gitignore
index.js
package.json

Use nyc for coverage

---

README.md
usage.md

Document tcurlrc

---

index.js

Fix case of the missing thrift file

---

index.js
test/as-json.js

Fix parsing for SHON --headers

---

logger.js

Fix raw output

---

logger.js
test/as-raw.js
test/as-thrift.js

Improve test coverage over logger with subprocesses

---

health.json
health.usage
index.js
man/tcurl.1
tcurl.json
tcurl.usage
usage.md

Implement routing delegate flag

---

index.js

Improve peer validation

---

README.md
health.json
health.usage
index.js
man/tcurl.1
tcurl.json
tcurl.usage
usage.md

Implement --cn flag to override headers.cn

---

index.js

Enable trace flags

---

index.js
test/as-json.js

Respect caller flag

---

as-http.js
test/as-http.js

Fix output for as=http

---

README.md

No longer under active development

---

index.js
man/tcurl.1
test/as-raw.js
test/as-thrift.js
test/health.js

Gently urge users to consider using yab.
